// Generated by scripts/gen-db-types.ts from supabase/migrations — do not edit.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: { PostgrestVersion: "12" };
  public: {
    Tables: {
      action_completions: {
        Row: {
          id: string;
          action_id: string;
          user_id: string;
          completed_at: string;
          reflection: string | null;
          minutes_spent: number | null;
        };
        Insert: {
          id?: string;
          action_id: string;
          user_id: string;
          completed_at?: string;
          reflection?: string | null;
          minutes_spent?: number | null;
        };
        Update: {
          id?: string;
          action_id?: string;
          user_id?: string;
          completed_at?: string;
          reflection?: string | null;
          minutes_spent?: number | null;
        };
        Relationships: [
          {
            foreignKeyName: "action_completions_action_id_user_id_fkey";
            columns: ["action_id", "user_id"];
            isOneToOne: false;
            referencedRelation: "daily_actions";
            referencedColumns: ["id", "user_id"];
          },
          {
            foreignKeyName: "action_completions_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      career_interests: {
        Row: {
          id: string;
          user_id: string;
          career_path_id: string | null;
          label: string;
          certainty: Database["public"]["Enums"]["certainty_level"] | null;
          position: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          career_path_id?: string | null;
          label: string;
          certainty?: Database["public"]["Enums"]["certainty_level"] | null;
          position?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          career_path_id?: string | null;
          label?: string;
          certainty?: Database["public"]["Enums"]["certainty_level"] | null;
          position?: number;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "career_interests_career_path_id_fkey";
            columns: ["career_path_id"];
            isOneToOne: false;
            referencedRelation: "career_paths";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "career_interests_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      career_paths: {
        Row: {
          id: string;
          slug: string;
          title: string;
          summary: string | null;
          category: string | null;
          onet_code: string | null;
          esco_uri: string | null;
          content: Json;
          sources: Json;
          last_verified_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          title: string;
          summary?: string | null;
          category?: string | null;
          onet_code?: string | null;
          esco_uri?: string | null;
          content?: Json;
          sources?: Json;
          last_verified_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          title?: string;
          summary?: string | null;
          category?: string | null;
          onet_code?: string | null;
          esco_uri?: string | null;
          content?: Json;
          sources?: Json;
          last_verified_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      daily_actions: {
        Row: {
          id: string;
          user_id: string;
          action_date: string;
          title: string;
          description: string | null;
          why: string;
          category: Database["public"]["Enums"]["action_category"];
          estimated_minutes: number;
          difficulty: Database["public"]["Enums"]["action_difficulty"];
          status: Database["public"]["Enums"]["action_status"];
          is_primary: boolean;
          milestone_id: string | null;
          replaced_by_id: string | null;
          resource_id: string | null;
          origin: Database["public"]["Enums"]["origin"];
          skip_reason: string | null;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          action_date: string;
          title: string;
          description?: string | null;
          why: string;
          category: Database["public"]["Enums"]["action_category"];
          estimated_minutes: number;
          difficulty?: Database["public"]["Enums"]["action_difficulty"];
          status?: Database["public"]["Enums"]["action_status"];
          is_primary?: boolean;
          milestone_id?: string | null;
          replaced_by_id?: string | null;
          resource_id?: string | null;
          origin?: Database["public"]["Enums"]["origin"];
          skip_reason?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          action_date?: string;
          title?: string;
          description?: string | null;
          why?: string;
          category?: Database["public"]["Enums"]["action_category"];
          estimated_minutes?: number;
          difficulty?: Database["public"]["Enums"]["action_difficulty"];
          status?: Database["public"]["Enums"]["action_status"];
          is_primary?: boolean;
          milestone_id?: string | null;
          replaced_by_id?: string | null;
          resource_id?: string | null;
          origin?: Database["public"]["Enums"]["origin"];
          skip_reason?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "daily_actions_milestone_id_user_id_fkey";
            columns: ["milestone_id", "user_id"];
            isOneToOne: false;
            referencedRelation: "roadmap_milestones";
            referencedColumns: ["id", "user_id"];
          },
          {
            foreignKeyName: "daily_actions_replaced_by_id_user_id_fkey";
            columns: ["replaced_by_id", "user_id"];
            isOneToOne: false;
            referencedRelation: "daily_actions";
            referencedColumns: ["id", "user_id"];
          },
          {
            foreignKeyName: "daily_actions_resource_id_fkey";
            columns: ["resource_id"];
            isOneToOne: false;
            referencedRelation: "resources";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "daily_actions_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      education_profiles: {
        Row: {
          id: string;
          user_id: string;
          university_id: string | null;
          school_name: string | null;
          level: string;
          year_in_school: string | null;
          expected_graduation: string | null;
          gpa: number | null;
          is_current: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          university_id?: string | null;
          school_name?: string | null;
          level: string;
          year_in_school?: string | null;
          expected_graduation?: string | null;
          gpa?: number | null;
          is_current?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          university_id?: string | null;
          school_name?: string | null;
          level?: string;
          year_in_school?: string | null;
          expected_graduation?: string | null;
          gpa?: number | null;
          is_current?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "education_profiles_university_id_fkey";
            columns: ["university_id"];
            isOneToOne: false;
            referencedRelation: "universities";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "education_profiles_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      majors: {
        Row: {
          id: string;
          university_id: string | null;
          name: string;
          department: string | null;
          degree_type: string | null;
          cip_code: string | null;
          source: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          university_id?: string | null;
          name: string;
          department?: string | null;
          degree_type?: string | null;
          cip_code?: string | null;
          source?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          university_id?: string | null;
          name?: string;
          department?: string | null;
          degree_type?: string | null;
          cip_code?: string | null;
          source?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "majors_university_id_fkey";
            columns: ["university_id"];
            isOneToOne: false;
            referencedRelation: "universities";
            referencedColumns: ["id"];
          },
        ];
      };
      mentor_conversations: {
        Row: {
          id: string;
          user_id: string;
          title: string | null;
          summary: string | null;
          summarized_through: string | null;
          kind: string;
          archived: boolean;
          last_message_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title?: string | null;
          summary?: string | null;
          summarized_through?: string | null;
          kind?: string;
          archived?: boolean;
          last_message_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string | null;
          summary?: string | null;
          summarized_through?: string | null;
          kind?: string;
          archived?: boolean;
          last_message_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "mentor_conversations_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      mentor_memories: {
        Row: {
          id: string;
          user_id: string;
          kind: Database["public"]["Enums"]["memory_kind"];
          content: string;
          importance: number;
          source_message_id: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          kind: Database["public"]["Enums"]["memory_kind"];
          content: string;
          importance?: number;
          source_message_id?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          kind?: Database["public"]["Enums"]["memory_kind"];
          content?: string;
          importance?: number;
          source_message_id?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "mentor_memories_source_message_id_user_id_fkey";
            columns: ["source_message_id", "user_id"];
            isOneToOne: false;
            referencedRelation: "mentor_messages";
            referencedColumns: ["id", "user_id"];
          },
          {
            foreignKeyName: "mentor_memories_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      mentor_messages: {
        Row: {
          id: string;
          conversation_id: string;
          user_id: string;
          role: Database["public"]["Enums"]["message_role"];
          content: string;
          suggestions: Json;
          model: string | null;
          input_tokens: number | null;
          output_tokens: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          user_id: string;
          role: Database["public"]["Enums"]["message_role"];
          content: string;
          suggestions?: Json;
          model?: string | null;
          input_tokens?: number | null;
          output_tokens?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          conversation_id?: string;
          user_id?: string;
          role?: Database["public"]["Enums"]["message_role"];
          content?: string;
          suggestions?: Json;
          model?: string | null;
          input_tokens?: number | null;
          output_tokens?: number | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "mentor_messages_conversation_id_user_id_fkey";
            columns: ["conversation_id", "user_id"];
            isOneToOne: false;
            referencedRelation: "mentor_conversations";
            referencedColumns: ["id", "user_id"];
          },
          {
            foreignKeyName: "mentor_messages_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      notification_preferences: {
        Row: {
          user_id: string;
          daily_reminder: Database["public"]["Enums"]["daily_reminder_frequency"];
          daily_reminder_time: string;
          opportunity_alerts: Database["public"]["Enums"]["opportunity_alert_level"];
          industry_updates: Database["public"]["Enums"]["industry_update_frequency"];
          weekly_checkin: boolean;
          weekly_checkin_day: number;
          channel_email: boolean;
          channel_push: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          daily_reminder?: Database["public"]["Enums"]["daily_reminder_frequency"];
          daily_reminder_time?: string;
          opportunity_alerts?: Database["public"]["Enums"]["opportunity_alert_level"];
          industry_updates?: Database["public"]["Enums"]["industry_update_frequency"];
          weekly_checkin?: boolean;
          weekly_checkin_day?: number;
          channel_email?: boolean;
          channel_push?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          daily_reminder?: Database["public"]["Enums"]["daily_reminder_frequency"];
          daily_reminder_time?: string;
          opportunity_alerts?: Database["public"]["Enums"]["opportunity_alert_level"];
          industry_updates?: Database["public"]["Enums"]["industry_update_frequency"];
          weekly_checkin?: boolean;
          weekly_checkin_day?: number;
          channel_email?: boolean;
          channel_push?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "notification_preferences_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      onboarding_responses: {
        Row: {
          id: string;
          user_id: string;
          question_key: string;
          answer: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          question_key: string;
          answer: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          question_key?: string;
          answer?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "onboarding_responses_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      professional_profiles: {
        Row: {
          user_id: string;
          current_title: string | null;
          current_employer: string | null;
          industry: string | null;
          years_experience: number | null;
          desired_next_role: string | null;
          desired_career: string | null;
          stuck_points: string | null;
          transferable_skills: string[];
          constraints_note: string | null;
          desired_timeline: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          current_title?: string | null;
          current_employer?: string | null;
          industry?: string | null;
          years_experience?: number | null;
          desired_next_role?: string | null;
          desired_career?: string | null;
          stuck_points?: string | null;
          transferable_skills?: string[];
          constraints_note?: string | null;
          desired_timeline?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          current_title?: string | null;
          current_employer?: string | null;
          industry?: string | null;
          years_experience?: number | null;
          desired_next_role?: string | null;
          desired_career?: string | null;
          stuck_points?: string | null;
          transferable_skills?: string[];
          constraints_note?: string | null;
          desired_timeline?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "professional_profiles_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      profiles: {
        Row: {
          id: string;
          display_name: string | null;
          first_name: string | null;
          user_type: Database["public"]["Enums"]["user_type"] | null;
          onboarding_status: Database["public"]["Enums"]["onboarding_status"];
          onboarding_step: string | null;
          onboarding_completed_at: string | null;
          timezone: string;
          current_city: string | null;
          current_region: string | null;
          current_country: string | null;
          relocation_preference:
            Database["public"]["Enums"]["relocation_preference"] | null;
          preferred_locations: string[];
          open_to_remote: boolean | null;
          career_certainty:
            Database["public"]["Enums"]["certainty_level"] | null;
          visibility: Database["public"]["Enums"]["visibility"];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          display_name?: string | null;
          first_name?: string | null;
          user_type?: Database["public"]["Enums"]["user_type"] | null;
          onboarding_status?: Database["public"]["Enums"]["onboarding_status"];
          onboarding_step?: string | null;
          onboarding_completed_at?: string | null;
          timezone?: string;
          current_city?: string | null;
          current_region?: string | null;
          current_country?: string | null;
          relocation_preference?:
            Database["public"]["Enums"]["relocation_preference"] | null;
          preferred_locations?: string[];
          open_to_remote?: boolean | null;
          career_certainty?:
            Database["public"]["Enums"]["certainty_level"] | null;
          visibility?: Database["public"]["Enums"]["visibility"];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          display_name?: string | null;
          first_name?: string | null;
          user_type?: Database["public"]["Enums"]["user_type"] | null;
          onboarding_status?: Database["public"]["Enums"]["onboarding_status"];
          onboarding_step?: string | null;
          onboarding_completed_at?: string | null;
          timezone?: string;
          current_city?: string | null;
          current_region?: string | null;
          current_country?: string | null;
          relocation_preference?:
            Database["public"]["Enums"]["relocation_preference"] | null;
          preferred_locations?: string[];
          open_to_remote?: boolean | null;
          career_certainty?:
            Database["public"]["Enums"]["certainty_level"] | null;
          visibility?: Database["public"]["Enums"]["visibility"];
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      recommendation_feedback: {
        Row: {
          id: string;
          recommendation_id: string;
          user_id: string;
          feedback: Database["public"]["Enums"]["feedback_type"];
          note: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          recommendation_id: string;
          user_id: string;
          feedback: Database["public"]["Enums"]["feedback_type"];
          note?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          recommendation_id?: string;
          user_id?: string;
          feedback?: Database["public"]["Enums"]["feedback_type"];
          note?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "recommendation_feedback_recommendation_id_user_id_fkey";
            columns: ["recommendation_id", "user_id"];
            isOneToOne: false;
            referencedRelation: "recommendations";
            referencedColumns: ["id", "user_id"];
          },
          {
            foreignKeyName: "recommendation_feedback_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      recommendations: {
        Row: {
          id: string;
          user_id: string;
          entity_type: Database["public"]["Enums"]["recommendation_entity"];
          entity_id: string | null;
          title: string;
          reason: string;
          signals: Json;
          score: number;
          surface: string;
          status: string;
          expires_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          entity_type: Database["public"]["Enums"]["recommendation_entity"];
          entity_id?: string | null;
          title: string;
          reason: string;
          signals?: Json;
          score?: number;
          surface?: string;
          status?: string;
          expires_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          entity_type?: Database["public"]["Enums"]["recommendation_entity"];
          entity_id?: string | null;
          title?: string;
          reason?: string;
          signals?: Json;
          score?: number;
          surface?: string;
          status?: string;
          expires_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "recommendations_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      resource_suggestions: {
        Row: {
          id: string;
          user_id: string;
          university_id: string;
          type: Database["public"]["Enums"]["university_resource_type"];
          name: string;
          url: string;
          note: string | null;
          status: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          university_id: string;
          type?: Database["public"]["Enums"]["university_resource_type"];
          name: string;
          url: string;
          note?: string | null;
          status?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          university_id?: string;
          type?: Database["public"]["Enums"]["university_resource_type"];
          name?: string;
          url?: string;
          note?: string | null;
          status?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "resource_suggestions_university_id_fkey";
            columns: ["university_id"];
            isOneToOne: false;
            referencedRelation: "universities";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "resource_suggestions_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      resources: {
        Row: {
          id: string;
          kind: Database["public"]["Enums"]["resource_kind"];
          title: string;
          description: string | null;
          url: string;
          author: string | null;
          provider: string | null;
          topics: string[];
          duration_minutes: number | null;
          cost: string | null;
          source_name: string;
          source_url: string | null;
          published_at: string | null;
          retrieved_at: string;
          last_verified_at: string | null;
          verification_status: Database["public"]["Enums"]["verification_status"];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          kind: Database["public"]["Enums"]["resource_kind"];
          title: string;
          description?: string | null;
          url: string;
          author?: string | null;
          provider?: string | null;
          topics?: string[];
          duration_minutes?: number | null;
          cost?: string | null;
          source_name: string;
          source_url?: string | null;
          published_at?: string | null;
          retrieved_at?: string;
          last_verified_at?: string | null;
          verification_status?: Database["public"]["Enums"]["verification_status"];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          kind?: Database["public"]["Enums"]["resource_kind"];
          title?: string;
          description?: string | null;
          url?: string;
          author?: string | null;
          provider?: string | null;
          topics?: string[];
          duration_minutes?: number | null;
          cost?: string | null;
          source_name?: string;
          source_url?: string | null;
          published_at?: string | null;
          retrieved_at?: string;
          last_verified_at?: string | null;
          verification_status?: Database["public"]["Enums"]["verification_status"];
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      roadmap_milestones: {
        Row: {
          id: string;
          roadmap_id: string;
          user_id: string;
          parent_id: string | null;
          horizon: Database["public"]["Enums"]["horizon"];
          title: string;
          description: string | null;
          why: string | null;
          category: Database["public"]["Enums"]["action_category"] | null;
          status: Database["public"]["Enums"]["milestone_status"];
          position: number;
          target_start: string | null;
          target_end: string | null;
          completed_at: string | null;
          origin: Database["public"]["Enums"]["origin"];
          source_message_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          roadmap_id: string;
          user_id: string;
          parent_id?: string | null;
          horizon: Database["public"]["Enums"]["horizon"];
          title: string;
          description?: string | null;
          why?: string | null;
          category?: Database["public"]["Enums"]["action_category"] | null;
          status?: Database["public"]["Enums"]["milestone_status"];
          position?: number;
          target_start?: string | null;
          target_end?: string | null;
          completed_at?: string | null;
          origin?: Database["public"]["Enums"]["origin"];
          source_message_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          roadmap_id?: string;
          user_id?: string;
          parent_id?: string | null;
          horizon?: Database["public"]["Enums"]["horizon"];
          title?: string;
          description?: string | null;
          why?: string | null;
          category?: Database["public"]["Enums"]["action_category"] | null;
          status?: Database["public"]["Enums"]["milestone_status"];
          position?: number;
          target_start?: string | null;
          target_end?: string | null;
          completed_at?: string | null;
          origin?: Database["public"]["Enums"]["origin"];
          source_message_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "roadmap_milestones_parent_id_user_id_fkey";
            columns: ["parent_id", "user_id"];
            isOneToOne: false;
            referencedRelation: "roadmap_milestones";
            referencedColumns: ["id", "user_id"];
          },
          {
            foreignKeyName: "roadmap_milestones_roadmap_id_user_id_fkey";
            columns: ["roadmap_id", "user_id"];
            isOneToOne: false;
            referencedRelation: "roadmaps";
            referencedColumns: ["id", "user_id"];
          },
          {
            foreignKeyName: "roadmap_milestones_source_message_fk";
            columns: ["source_message_id", "user_id"];
            isOneToOne: false;
            referencedRelation: "mentor_messages";
            referencedColumns: ["id", "user_id"];
          },
          {
            foreignKeyName: "roadmap_milestones_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      roadmap_revisions: {
        Row: {
          id: string;
          roadmap_id: string;
          user_id: string;
          cause: string;
          summary: string;
          changes: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          roadmap_id: string;
          user_id: string;
          cause: string;
          summary: string;
          changes?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          roadmap_id?: string;
          user_id?: string;
          cause?: string;
          summary?: string;
          changes?: Json;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "roadmap_revisions_roadmap_id_user_id_fkey";
            columns: ["roadmap_id", "user_id"];
            isOneToOne: false;
            referencedRelation: "roadmaps";
            referencedColumns: ["id", "user_id"];
          },
          {
            foreignKeyName: "roadmap_revisions_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      roadmaps: {
        Row: {
          id: string;
          user_id: string;
          kind: Database["public"]["Enums"]["roadmap_kind"];
          title: string;
          north_star: string | null;
          mode: string;
          status: string;
          version: number;
          origin: Database["public"]["Enums"]["origin"];
          visibility: Database["public"]["Enums"]["visibility"];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          kind?: Database["public"]["Enums"]["roadmap_kind"];
          title: string;
          north_star?: string | null;
          mode?: string;
          status?: string;
          version?: number;
          origin?: Database["public"]["Enums"]["origin"];
          visibility?: Database["public"]["Enums"]["visibility"];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          kind?: Database["public"]["Enums"]["roadmap_kind"];
          title?: string;
          north_star?: string | null;
          mode?: string;
          status?: string;
          version?: number;
          origin?: Database["public"]["Enums"]["origin"];
          visibility?: Database["public"]["Enums"]["visibility"];
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "roadmaps_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      saved_resources: {
        Row: {
          id: string;
          user_id: string;
          resource_id: string | null;
          university_resource_id: string | null;
          note: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          resource_id?: string | null;
          university_resource_id?: string | null;
          note?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          resource_id?: string | null;
          university_resource_id?: string | null;
          note?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "saved_resources_resource_id_fkey";
            columns: ["resource_id"];
            isOneToOne: false;
            referencedRelation: "resources";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "saved_resources_university_resource_id_fkey";
            columns: ["university_resource_id"];
            isOneToOne: false;
            referencedRelation: "university_resources";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "saved_resources_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      skill_evidence: {
        Row: {
          id: string;
          user_id: string;
          user_skill_id: string;
          kind: string;
          title: string;
          description: string | null;
          url: string | null;
          occurred_on: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          user_skill_id: string;
          kind: string;
          title: string;
          description?: string | null;
          url?: string | null;
          occurred_on?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          user_skill_id?: string;
          kind?: string;
          title?: string;
          description?: string | null;
          url?: string | null;
          occurred_on?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "skill_evidence_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "skill_evidence_user_skill_id_user_id_fkey";
            columns: ["user_skill_id", "user_id"];
            isOneToOne: false;
            referencedRelation: "user_skills";
            referencedColumns: ["id", "user_id"];
          },
        ];
      };
      skills: {
        Row: {
          id: string;
          name: string;
          category: Database["public"]["Enums"]["skill_category"];
          esco_uri: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          category: Database["public"]["Enums"]["skill_category"];
          esco_uri?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          category?: Database["public"]["Enums"]["skill_category"];
          esco_uri?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      universities: {
        Row: {
          id: string;
          name: string;
          search_name: string;
          domains: string[];
          primary_domain: string | null;
          country: string | null;
          country_code: string | null;
          state_region: string | null;
          city: string | null;
          latitude: number | null;
          longitude: number | null;
          website_url: string | null;
          career_center_url: string | null;
          clubs_directory_url: string | null;
          career_portal_url: string | null;
          entrepreneurship_url: string | null;
          academic_advising_url: string | null;
          alumni_url: string | null;
          source: string;
          source_id: string | null;
          metadata: Json;
          last_verified_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          search_name: string;
          domains?: string[];
          primary_domain?: string | null;
          country?: string | null;
          country_code?: string | null;
          state_region?: string | null;
          city?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          website_url?: string | null;
          career_center_url?: string | null;
          clubs_directory_url?: string | null;
          career_portal_url?: string | null;
          entrepreneurship_url?: string | null;
          academic_advising_url?: string | null;
          alumni_url?: string | null;
          source: string;
          source_id?: string | null;
          metadata?: Json;
          last_verified_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          search_name?: string;
          domains?: string[];
          primary_domain?: string | null;
          country?: string | null;
          country_code?: string | null;
          state_region?: string | null;
          city?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          website_url?: string | null;
          career_center_url?: string | null;
          clubs_directory_url?: string | null;
          career_portal_url?: string | null;
          entrepreneurship_url?: string | null;
          academic_advising_url?: string | null;
          alumni_url?: string | null;
          source?: string;
          source_id?: string | null;
          metadata?: Json;
          last_verified_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      university_resources: {
        Row: {
          id: string;
          university_id: string;
          type: Database["public"]["Enums"]["university_resource_type"];
          name: string;
          description: string | null;
          url: string;
          source_url: string | null;
          source_name: string | null;
          verification_status: Database["public"]["Enums"]["verification_status"];
          retrieved_at: string | null;
          last_verified_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          university_id: string;
          type: Database["public"]["Enums"]["university_resource_type"];
          name: string;
          description?: string | null;
          url: string;
          source_url?: string | null;
          source_name?: string | null;
          verification_status?: Database["public"]["Enums"]["verification_status"];
          retrieved_at?: string | null;
          last_verified_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          university_id?: string;
          type?: Database["public"]["Enums"]["university_resource_type"];
          name?: string;
          description?: string | null;
          url?: string;
          source_url?: string | null;
          source_name?: string | null;
          verification_status?: Database["public"]["Enums"]["verification_status"];
          retrieved_at?: string | null;
          last_verified_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "university_resources_university_id_fkey";
            columns: ["university_id"];
            isOneToOne: false;
            referencedRelation: "universities";
            referencedColumns: ["id"];
          },
        ];
      };
      user_goals: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          description: string | null;
          horizon: Database["public"]["Enums"]["horizon"];
          status: Database["public"]["Enums"]["goal_status"];
          origin: Database["public"]["Enums"]["origin"];
          target_date: string | null;
          position: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          description?: string | null;
          horizon?: Database["public"]["Enums"]["horizon"];
          status?: Database["public"]["Enums"]["goal_status"];
          origin?: Database["public"]["Enums"]["origin"];
          target_date?: string | null;
          position?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          description?: string | null;
          horizon?: Database["public"]["Enums"]["horizon"];
          status?: Database["public"]["Enums"]["goal_status"];
          origin?: Database["public"]["Enums"]["origin"];
          target_date?: string | null;
          position?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "user_goals_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      user_majors: {
        Row: {
          id: string;
          user_id: string;
          education_profile_id: string;
          major_id: string | null;
          name: string;
          kind: string;
          position: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          education_profile_id: string;
          major_id?: string | null;
          name: string;
          kind: string;
          position?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          education_profile_id?: string;
          major_id?: string | null;
          name?: string;
          kind?: string;
          position?: number;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "user_majors_education_profile_id_user_id_fkey";
            columns: ["education_profile_id", "user_id"];
            isOneToOne: false;
            referencedRelation: "education_profiles";
            referencedColumns: ["id", "user_id"];
          },
          {
            foreignKeyName: "user_majors_major_id_fkey";
            columns: ["major_id"];
            isOneToOne: false;
            referencedRelation: "majors";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "user_majors_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      user_preferences: {
        Row: {
          user_id: string;
          preferred_industries: string[];
          companies_admired: string[];
          lifestyle_priorities: string[];
          skills_to_learn: string[];
          salary_goal: string | null;
          grad_school_interest:
            Database["public"]["Enums"]["certainty_level"] | null;
          entrepreneurship_interest:
            Database["public"]["Enums"]["certainty_level"] | null;
          five_year_vision: string | null;
          created_at: string;
          updated_at: string;
          interests: string[];
        };
        Insert: {
          user_id: string;
          preferred_industries?: string[];
          companies_admired?: string[];
          lifestyle_priorities?: string[];
          skills_to_learn?: string[];
          salary_goal?: string | null;
          grad_school_interest?:
            Database["public"]["Enums"]["certainty_level"] | null;
          entrepreneurship_interest?:
            Database["public"]["Enums"]["certainty_level"] | null;
          five_year_vision?: string | null;
          created_at?: string;
          updated_at?: string;
          interests?: string[];
        };
        Update: {
          user_id?: string;
          preferred_industries?: string[];
          companies_admired?: string[];
          lifestyle_priorities?: string[];
          skills_to_learn?: string[];
          salary_goal?: string | null;
          grad_school_interest?:
            Database["public"]["Enums"]["certainty_level"] | null;
          entrepreneurship_interest?:
            Database["public"]["Enums"]["certainty_level"] | null;
          five_year_vision?: string | null;
          created_at?: string;
          updated_at?: string;
          interests?: string[];
        };
        Relationships: [
          {
            foreignKeyName: "user_preferences_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      user_skills: {
        Row: {
          id: string;
          user_id: string;
          skill_id: string | null;
          name: string;
          category: Database["public"]["Enums"]["skill_category"];
          status: string;
          level: string | null;
          origin: Database["public"]["Enums"]["origin"];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          skill_id?: string | null;
          name: string;
          category?: Database["public"]["Enums"]["skill_category"];
          status?: string;
          level?: string | null;
          origin?: Database["public"]["Enums"]["origin"];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          skill_id?: string | null;
          name?: string;
          category?: Database["public"]["Enums"]["skill_category"];
          status?: string;
          level?: string | null;
          origin?: Database["public"]["Enums"]["origin"];
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "user_skills_skill_id_fkey";
            columns: ["skill_id"];
            isOneToOne: false;
            referencedRelation: "skills";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "user_skills_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      venture_profiles: {
        Row: {
          id: string;
          user_id: string;
          is_primary: boolean;
          has_idea: Database["public"]["Enums"]["certainty_level"] | null;
          idea_summary: string | null;
          industry: string | null;
          offering_type: string | null;
          channel: string | null;
          stage: string | null;
          target_customer: string | null;
          starting_capital_range: string | null;
          experience_summary: string | null;
          location: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          is_primary?: boolean;
          has_idea?: Database["public"]["Enums"]["certainty_level"] | null;
          idea_summary?: string | null;
          industry?: string | null;
          offering_type?: string | null;
          channel?: string | null;
          stage?: string | null;
          target_customer?: string | null;
          starting_capital_range?: string | null;
          experience_summary?: string | null;
          location?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          is_primary?: boolean;
          has_idea?: Database["public"]["Enums"]["certainty_level"] | null;
          idea_summary?: string | null;
          industry?: string | null;
          offering_type?: string | null;
          channel?: string | null;
          stage?: string | null;
          target_customer?: string | null;
          starting_capital_range?: string | null;
          experience_summary?: string | null;
          location?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "venture_profiles_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      weekly_checkins: {
        Row: {
          id: string;
          user_id: string;
          week_start: string;
          progress_note: string | null;
          changes_note: string | null;
          difficulties_note: string | null;
          next_priority_note: string | null;
          mentor_summary: string | null;
          applied_changes: Json;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          week_start: string;
          progress_note?: string | null;
          changes_note?: string | null;
          difficulties_note?: string | null;
          next_priority_note?: string | null;
          mentor_summary?: string | null;
          applied_changes?: Json;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          week_start?: string;
          progress_note?: string | null;
          changes_note?: string | null;
          difficulties_note?: string | null;
          next_priority_note?: string | null;
          mentor_summary?: string | null;
          applied_changes?: Json;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "weekly_checkins_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      weekly_priorities: {
        Row: {
          id: string;
          user_id: string;
          week_start: string;
          title: string;
          why: string | null;
          category: Database["public"]["Enums"]["action_category"] | null;
          milestone_id: string | null;
          status: string;
          position: number;
          origin: Database["public"]["Enums"]["origin"];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          week_start: string;
          title: string;
          why?: string | null;
          category?: Database["public"]["Enums"]["action_category"] | null;
          milestone_id?: string | null;
          status?: string;
          position?: number;
          origin?: Database["public"]["Enums"]["origin"];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          week_start?: string;
          title?: string;
          why?: string | null;
          category?: Database["public"]["Enums"]["action_category"] | null;
          milestone_id?: string | null;
          status?: string;
          position?: number;
          origin?: Database["public"]["Enums"]["origin"];
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "weekly_priorities_milestone_id_user_id_fkey";
            columns: ["milestone_id", "user_id"];
            isOneToOne: false;
            referencedRelation: "roadmap_milestones";
            referencedColumns: ["id", "user_id"];
          },
          {
            foreignKeyName: "weekly_priorities_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: { [_ in never]: never };
    Functions: {
      get_progress_summary: {
        Args: { p_since?: string; p_today?: string };
        Returns: Json;
      };
      search_universities: {
        Args: { p_query: string; p_country_code?: string; p_limit?: number };
        Returns: Database["public"]["Tables"]["universities"]["Row"][];
      };
    };
    Enums: {
      origin: "ai" | "user" | "checkin" | "chat" | "system" | "onboarding";
      horizon: "long_term" | "year" | "term" | "month" | "week" | "today";
      user_type:
        | "college_student"
        | "high_school_student"
        | "recent_graduate"
        | "working_professional"
        | "entrepreneur"
        | "career_changer"
        | "exploring";
      visibility: "private" | "public";
      goal_status: "active" | "achieved" | "paused" | "dropped";
      memory_kind:
        "fact" | "preference" | "goal" | "concern" | "decision" | "context";
      message_role: "user" | "assistant";
      roadmap_kind: "career" | "venture";
      action_status: "pending" | "completed" | "skipped" | "replaced";
      feedback_type:
        | "saved"
        | "dismissed"
        | "not_interested"
        | "joined"
        | "completed"
        | "helpful"
        | "not_helpful";
      resource_kind:
        | "course"
        | "video"
        | "article"
        | "book"
        | "certification"
        | "tutorial"
        | "project"
        | "podcast"
        | "community"
        | "tool";
      skill_category:
        | "technical"
        | "industry"
        | "communication"
        | "leadership"
        | "business"
        | "networking"
        | "portfolio"
        | "interviewing";
      action_category:
        | "skills"
        | "networking"
        | "experience"
        | "career_exploration"
        | "applications"
        | "learning"
        | "business";
      certainty_level: "yes" | "kind_of" | "no_idea";
      milestone_status: "not_started" | "in_progress" | "completed" | "skipped";
      action_difficulty: "lighter" | "standard" | "stretch";
      onboarding_status: "not_started" | "in_progress" | "completed";
      verification_status: "verified" | "unverified" | "stale" | "broken";
      recommendation_entity:
        | "resource"
        | "university_resource"
        | "club"
        | "person"
        | "opportunity"
        | "news_item"
        | "career_path"
        | "milestone"
        | "project_idea";
      relocation_preference:
        "stay" | "specific" | "open" | "remote" | "not_sure";
      opportunity_alert_level: "off" | "important" | "all";
      daily_reminder_frequency: "off" | "daily";
      university_resource_type:
        | "career_center"
        | "career_portal"
        | "academic_advising"
        | "internships"
        | "tutoring"
        | "alumni"
        | "entrepreneurship"
        | "incubator"
        | "research"
        | "study_abroad"
        | "scholarships"
        | "professional_development"
        | "departments"
        | "career_fairs"
        | "student_organizations"
        | "library"
        | "wellbeing"
        | "other";
      industry_update_frequency: "off" | "daily_digest" | "weekly_digest";
    };
    CompositeTypes: { [_ in never]: never };
  };
};

type PublicSchema = Database["public"];
export type Tables<T extends keyof PublicSchema["Tables"]> =
  PublicSchema["Tables"][T]["Row"];
export type TablesInsert<T extends keyof PublicSchema["Tables"]> =
  PublicSchema["Tables"][T]["Insert"];
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> =
  PublicSchema["Tables"][T]["Update"];
export type Enums<T extends keyof PublicSchema["Enums"]> =
  PublicSchema["Enums"][T];
