/**
 * Generates src/types/database.ts from the migrated schema, in the same shape
 * as `supabase gen types typescript` (usable with the typed Supabase client).
 * Run via `npm run db:types` (applies migrations to a scratch DB first).
 */
import { readFileSync, writeFileSync } from "node:fs";

type Column = {
  name: string;
  type: string;
  typtype: string;
  elem: string | null;
  elemtyptype: string | null;
  nullable: boolean;
  hasDefault: boolean;
  generated: boolean;
};
type Relationship = {
  foreignKeyName: string;
  columns: string[];
  isOneToOne: boolean;
  referencedRelation: string;
  referencedColumns: string[];
};
type Table = { name: string; columns: Column[]; relationships: Relationship[] };
type Fn = {
  name: string;
  args: { name: string; type: string; optional: boolean }[];
  returns: string;
  retset: boolean;
};
type Schema = {
  tables: Table[];
  enums: Record<string, string[]>;
  functions: Fn[];
};

const schema = JSON.parse(readFileSync(0, "utf8")) as Schema;
const enumNames = new Set(Object.keys(schema.enums ?? {}));
const tableNames = new Set(schema.tables.map((t) => t.name));

const SCALARS: Record<string, string> = {
  uuid: "string",
  text: "string",
  varchar: "string",
  bpchar: "string",
  citext: "string",
  date: "string",
  time: "string",
  timetz: "string",
  timestamp: "string",
  timestamptz: "string",
  interval: "string",
  int2: "number",
  int4: "number",
  int8: "number",
  float4: "number",
  float8: "number",
  numeric: "number",
  bool: "boolean",
  json: "Json",
  jsonb: "Json",
  // format_type() spellings (used for function signatures)
  "text[]": "string[]",
  integer: "number",
  smallint: "number",
  bigint: "number",
  real: "number",
  "double precision": "number",
  boolean: "boolean",
  "timestamp with time zone": "string",
  "character varying": "string",
};

function scalar(type: string, isEnum: boolean): string {
  if (isEnum) return `Database["public"]["Enums"]["${type}"]`;
  const ts = SCALARS[type];
  if (!ts) throw new Error(`Unmapped Postgres type: ${type}`);
  return ts;
}

function columnType(c: Column): string {
  if (c.elem) return `${scalar(c.elem, c.elemtyptype === "e")}[]`;
  return scalar(c.type, c.typtype === "e");
}

function fnType(pgType: string): string {
  const bare = pgType.replace(/^public\./, "");
  if (enumNames.has(bare)) return `Database["public"]["Enums"]["${bare}"]`;
  if (tableNames.has(bare))
    return `Database["public"]["Tables"]["${bare}"]["Row"]`;
  return scalar(pgType, false);
}

const ind = (n: number) => "  ".repeat(n);
const out: string[] = [];
out.push(
  "// Generated by scripts/gen-db-types.ts from supabase/migrations — do not edit.",
  "export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];",
  "",
  "export type Database = {",
  `${ind(1)}__InternalSupabase: { PostgrestVersion: "12" };`,
  `${ind(1)}public: {`,
  `${ind(2)}Tables: {`,
);
for (const t of schema.tables) {
  out.push(`${ind(3)}${t.name}: {`);
  for (const mode of ["Row", "Insert", "Update"] as const) {
    out.push(`${ind(4)}${mode}: {`);
    for (const c of t.columns) {
      if (mode !== "Row" && c.generated) continue;
      const base = columnType(c) + (c.nullable ? " | null" : "");
      const optional =
        mode === "Update" ||
        (mode === "Insert" && (c.nullable || c.hasDefault));
      out.push(`${ind(5)}${c.name}${optional ? "?" : ""}: ${base};`);
    }
    out.push(`${ind(4)}};`);
  }
  out.push(`${ind(4)}Relationships: [`);
  for (const r of t.relationships) {
    out.push(
      `${ind(5)}{ foreignKeyName: "${r.foreignKeyName}"; columns: ${JSON.stringify(r.columns)}; isOneToOne: false; referencedRelation: "${r.referencedRelation}"; referencedColumns: ${JSON.stringify(r.referencedColumns)} },`,
    );
  }
  out.push(`${ind(4)}];`, `${ind(3)}};`);
}
out.push(
  `${ind(2)}};`,
  `${ind(2)}Views: { [_ in never]: never };`,
  `${ind(2)}Functions: {`,
);
for (const f of schema.functions ?? []) {
  const args = f.args.length
    ? `{ ${f.args.map((a) => `${a.name}${a.optional ? "?" : ""}: ${fnType(a.type)}`).join("; ")} }`
    : "Record<PropertyKey, never>";
  const ret = fnType(f.returns) + (f.retset ? "[]" : "");
  out.push(`${ind(3)}${f.name}: { Args: ${args}; Returns: ${ret} };`);
}
out.push(`${ind(2)}};`, `${ind(2)}Enums: {`);
for (const [name, labels] of Object.entries(schema.enums ?? {})) {
  out.push(
    `${ind(3)}${name}: ${labels.map((l) => JSON.stringify(l)).join(" | ")};`,
  );
}
out.push(
  `${ind(2)}};`,
  `${ind(2)}CompositeTypes: { [_ in never]: never };`,
  `${ind(1)}};`,
  "};",
  "",
);
out.push(
  'type PublicSchema = Database["public"];',
  'export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"];',
  'export type TablesInsert<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Insert"];',
  'export type TablesUpdate<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Update"];',
  'export type Enums<T extends keyof PublicSchema["Enums"]> = PublicSchema["Enums"][T];',
  "",
);

writeFileSync(process.argv[2] ?? "src/types/database.ts", out.join("\n"));
console.log(
  `Wrote ${schema.tables.length} tables, ${Object.keys(schema.enums ?? {}).length} enums, ${(schema.functions ?? []).length} functions`,
);
