/**
 * Imports the worldwide university list into `public.universities`.
 *
 *   npm run db:import-universities                 # fetch dataset, upsert via Supabase (service role)
 *   npm run db:import-universities -- --file x.json
 *   npm run db:import-universities -- --sql out.sql  # write SQL instead (for psql / SQL editor)
 *
 * Re-running is safe: rows upsert on (source, source_id) and existing
 * enrichment columns (career center URLs, coordinates...) are left untouched.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { createClient } from "@supabase/supabase-js";
import {
  HIPO_DATASET_URL,
  parseHipoDataset,
  type UniversityUpsert,
} from "../src/lib/universities/hipo";

function arg(name: string): string | undefined {
  const i = process.argv.indexOf(`--${name}`);
  return i >= 0 ? process.argv[i + 1] : undefined;
}

function sqlString(v: string | null): string {
  return v === null ? "null" : `'${v.replace(/'/g, "''")}'`;
}

function sqlArray(xs: string[]): string {
  return xs.length
    ? `array[${xs.map(sqlString).join(",")}]::text[]`
    : "'{}'::text[]";
}

function toSql(rows: UniversityUpsert[]): string {
  const out = ["-- Generated by scripts/import-universities.ts", "begin;"];
  for (let i = 0; i < rows.length; i += 500) {
    const values = rows
      .slice(i, i + 500)
      .map(
        (r) =>
          `(${[
            sqlString(r.name),
            sqlString(r.search_name),
            sqlArray(r.domains),
            sqlString(r.primary_domain),
            sqlString(r.country),
            sqlString(r.country_code),
            sqlString(r.state_region),
            sqlString(r.website_url),
            sqlString(r.source),
            sqlString(r.source_id),
          ].join(",")})`,
      );
    out.push(
      `insert into public.universities (name, search_name, domains, primary_domain, country, country_code, state_region, website_url, source, source_id) values\n${values.join(",\n")}\non conflict (source, source_id) do update set name = excluded.name, search_name = excluded.search_name, domains = excluded.domains, primary_domain = excluded.primary_domain, country = excluded.country, country_code = excluded.country_code, state_region = coalesce(public.universities.state_region, excluded.state_region), website_url = coalesce(public.universities.website_url, excluded.website_url);`,
    );
  }
  out.push("commit;", "");
  return out.join("\n");
}

async function main() {
  const file = arg("file");
  const sqlOut = arg("sql");

  const raw: unknown = file
    ? JSON.parse(readFileSync(file, "utf8"))
    : await fetch(HIPO_DATASET_URL).then((r) => {
        if (!r.ok) throw new Error(`Dataset download failed: HTTP ${r.status}`);
        return r.json();
      });

  const { rows, skipped } = parseHipoDataset(raw);
  console.log(`Parsed ${rows.length} universities (${skipped} skipped/merged)`);

  if (sqlOut) {
    writeFileSync(sqlOut, toSql(rows));
    console.log(`Wrote ${sqlOut}`);
    return;
  }

  try {
    process.loadEnvFile(".env.local");
  } catch {
    // Env may come from the shell instead.
  }
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) {
    throw new Error(
      "Set NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY, or use --sql <file>.",
    );
  }
  const supabase = createClient(url, key, { auth: { persistSession: false } });

  let done = 0;
  for (let i = 0; i < rows.length; i += 500) {
    const batch = rows.slice(i, i + 500);
    const { error } = await supabase
      .from("universities")
      .upsert(batch, {
        onConflict: "source,source_id",
        ignoreDuplicates: false,
      });
    if (error) throw new Error(`Upsert failed at row ${i}: ${error.message}`);
    done += batch.length;
    process.stdout.write(`\rUpserted ${done}/${rows.length}`);
  }
  console.log("\nDone.");
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
